sonar.projectKey=aceest-fitness-gym
sonar.projectName=ACEest Fitness Gym
sonar.projectVersion=1.0

sonar.sources=backend/app
sonar.tests=backend/tests
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=backend/reports/coverage.xml
sonar.python.xunit.reportPath=backend/reports/pytest.xml
sonar.exclusions=backend/venv/**,backend/.pytest_cache/**,backend/reports/**
sonar.coverage.exclusions=backend/tests/**
